### ISSUE TITLE
Send Feedback Button alignment

### ISSUE THREAD

**Issue by TheCakeGit** [DNNCommunity/DNN.Feedback#26]
Hi

This is an age old issue, it's probably resolved but I can't seem to align the Send button no matter what I do. For example it would be cool to center align this Send button button... Any ideas.. thanks!

https://imgur.com/a/e6k0g

**Comment by valadas** [comment]
@TheCakeGit This would be a style choice that you can include in your skin or your page css.

One way to center the button could be like this: 

```css
.FeedbackForm ul.dnnActions {
    width: 100%;
}

.FeedbackForm ul.dnnActions li{
    display:block;
    margin: 0 auto;
    float:none;
    text-align:center;
}
```
